### ISSUE TITLE
Traduzir Avançado

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/vue-router#2]

**Comment by esron** [comment]
Olá @ErickPetru , 

Posso ajudar nessas traduções?

**Comment by ErickPetru** [comment]
Olá @esron, certamente. Faz um _fork_ e traduz os arquivos que puder, depois envia aqui como _pull request_. Apesar do pessoal estar trabalhando mais nos arquivos "Essenciais" por enquanto, é legal também avisar aqui nessa _issue_ em qual for trabalhar, para não correr o risco de alguém começar ao mesmo tempo.

**Comment by esron** [comment]
Beleza!!

**Comment by esron** [comment]
Estou trabalhando no arquivo `data-fetching.md`

**Comment by esron** [comment]
Olá @ErickPetru , passando pra avisar que estou trabalhando no arquivo `lazy-loading.md`

**Comment by gab0gomes** [comment]
Arquivos com tradução iniciada ou finalizada:

* [x] data-fetching.md
* [x] lazy-loading.md
* [x] meta.md
* [x] navigation-guards.md
* [x] scroll-behavior.md
* [x] transitions.md

**Comment by gab0gomes** [comment]
Hey, @ErickPetru.

Acho que acabamos por aqui! :tada:
