### ISSUE TITLE
Tradução completa

### ISSUE THREAD

**Issue by nazarepiedady** [vuejs-br/vue-router#26]
Eu pessoalmente já traduzi, todos documentos referentes a documentação do Vue Router, apenas faltando correções de falhas na tradução caso houverem. Aqui deixo o [local dos documentos](https://github.com/nazarepiedady/vue-router-pt-doc).

**Comment by ErickPetru** [comment]
Olá @nazarepiedady, você traduziu em relação à versão mais recente do repositório principal (https://github.com/vuejs/vue-router)?

**Comment by nazarepiedady** [comment]
Exatamente. Eu comecei no mês de Novembro e terminei ela no mês atual.

**Comment by ErickPetru** [comment]
Que legal @nazarepiedady, por favor, envie um _pull request_ para este repositório (lembrando que nossa tradução fica dentro da pasta `pt`). Depois que o _merge_ for realizado, poderei enviar a solicitação ao _core team_ para que integrem no repositório principal.
