### ISSUE TITLE
Traduzir Essenciais

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/vue-router#3]

**Comment by gab0gomes** [comment]
Arquivos com tradução finalizada ou iniciada:

- [x] dynamic-matching.md
- [x] history-mode.md
- [x] named-routes.md
- [x] named-views.md
- [x] navigation.md
- [x] nested-routes.md
- [x] passing-props.md
- [x] redirect-and-alias.md

**Comment by vilaboim** [comment]
@ErickPetru e @Gabrielr2508 vou traduzir o `history-mode.md`, ok?

**Comment by gab0gomes** [comment]
> @ErickPetru e @Gabrielr2508 vou traduzir o `history-mode.md`, ok?

Boa, vai nessa!

Já marquei nas traduções iniciadas. :)

**Comment by lucasnasm** [comment]
@Gabrielr2508 traduzindo `named-routes.md`.

**Comment by gab0gomes** [comment]
> @Gabrielr2508 traduzindo `named-routes.md`.

Nice!

**Comment by gabidombrowski** [comment]
@Gabrielr2508 Traduzindo `navigation.md`.

**Comment by gab0gomes** [comment]
Hey, @ErickPetru. Finalizamos essa parte! :smile: 

As PRs estão abertas.
