### ISSUE TITLE
Traduzir Sumário e Instalação

### ISSUE THREAD

**Issue by ErickPetru** [vuejs-br/vue-router#4]

**Comment by leandroruel** [comment]
já traduzi esses dois. tá no meu repositório

**Comment by ErickPetru** [comment]
Ok, pode fazer _pull request_ que atribuímos para alguém revisar.

**Comment by leandroruel** [comment]
eu forkei o repo, devo configurar um branch novo para fazer o pull?

**Comment by ErickPetru** [comment]
Pode fazer _pull_ com suas alterações diretamente aqui, colocamos alguém para revisão.

**Comment by GuiDevloper** [comment]
Hey @leandroruel ainda pensa em continuar e fazer a PR?

@ErickPetru o que acha de depois atualizar este _fork_ para traduzirmos o mais atual?

**Comment by leandroruel** [comment]
Oi, esse ano teve tanta coisa acontecendo que nem tive tempo direito de dar pull aqui, mas se não me engano eu tenho essa parte ja traduzida, só não sei se mudou alguma coisa de maio para cá nessa seção da documentação

**Comment by GuiDevloper** [comment]
Neste _fork_ parece que não mudou, se fizer a PR e for atualizado pro atual talvez fique algo pra trás da sua tradução.
De qualquer forma é importante que mande, por ser trabalho feito e ficará registrado.

**Comment by leandroruel** [comment]
tô mandando uma PR então, vai ter uma pastinha nova chamada "pt-br",
qualquer problema na tradução, sou apenas eu, ou qualquer um pode corrigir?

**Comment by GuiDevloper** [comment]
tudo segue o que o Erick disse, pode ser que tenha revisão da equipe VueBr se necessário

**Comment by gab0gomes** [comment]
Traduzi a instalação em #7. Acho que o arquivo de sumário não existe mais, ou está com outro nome.

**Comment by ErickPetru** [comment]
Tem razão @Gabrielr2508, depois da migração para VuePress, acredito que o arquivo `.vuepress/config.js` que você traduziu atende o que o sumário fazia. Fechando esta _issue_.
