### ISSUE TITLE
Reaproveitamento da tradução

### ISSUE THREAD

**Issue by angeliski** [vuejs-br/vue-router#5]
Salve @ErickPetru 
O @felipe-ssilva começou a tradução (a um tempo atrás) no repositório do vue-router:
https://github.com/vuejs/vue-router/pull/2081

Você vê algum problema em reaproveitar esse trabalho dele?
Tem algumas coisas que podem ser mudadas/melhoradas, mas acho que seria bacana a gente fazer uso desse esforço que ele já teve.

O que você acha?

**Comment by felipe-ssilva** [comment]
@angeliski e @ErickPetru contem comigo.

**Comment by ErickPetru** [comment]
Olá @angeliski e @felipe-ssilva. Desculpem a demora, viagem de começo de ano.

Pois bem, não vejo problemas em aproveitar a tradução iniciada e depois buscar as atualizações mais recentes do repositório original para traduzi-las.

Como o Eduardo comentou no repositório oficial, quando tivermos a tradução madura deste documentação, podemos enviar o pull request para lá e depois solicitar o registro no Git Localize do projeto, o que vai facilitar bastante manutenções futuras.

**Comment by angeliski** [comment]
Maravilha! 
Você pode fazer isso @felipe-ssilva ? Se você precisar de ajuda (ou estiver sem tempo de fazer) eu posso ajudar :)

**Comment by wilmersondasilva** [comment]
Oi, pessoal,

Como ficou o reaproveitamento do que o @felipe-ssilva começou? Queria ajudar também.

**Comment by angeliski** [comment]
Olá @wilmersondasilva 
Na realidade, acho que não houve avanço nisso. Acredito que podemos pegar as issues e ir avançando (Seja usando o que já foi traduzido ou não)

**Comment by ErickPetru** [comment]
Olá @wilmersondasilva, é como o @angeliski disse, não houve avanço. Eu sugiro pegar as versões mais recentes dos arquivos em `/docs` a partir do repositório oficial para criar uma pasta `/docs/br` e ir traduzindo, aproveitando o trabalho do @felipe-ssilva nos trechos que não sofreram alterações depois disso e complementando com as traduções do que tiver sido atualizado.
